### ISSUE TITLE
Add an option to use storethehash as an immutable storage

### ISSUE THREAD

**Issue by adlrocha** [ipld/go-storethehash#1]
Consider if it is worth explicitly creating an option to set up storethehash as an immutable store. (Although `store.Put` already implicitly checks if key and value have changed we can save this check and improve performance by explicitly setting storethehash as immutable).

Additional context: https://github.com/hannahhoward/go-storethehash/pull/2#discussion_r661658867

**Comment by gammazero** [comment]
Fixed by #45
