### ISSUE TITLE
Document Flush, Sync and Close behaviour for FreeList

### ISSUE THREAD

**Issue by iand** [ipld/go-storethehash#17]
What is the expected interplay between Flush, Sync and Close.

[Sync](https://github.com/ipld/go-storethehash/blob/41b16c131842abc8ec6cd4ba236e439d2bf11440/store/freelist/freelist.go#L99) doesn't call Flush.

[Flush](https://github.com/ipld/go-storethehash/blob/41b16c131842abc8ec6cd4ba236e439d2bf11440/store/freelist/freelist.go#L95) commits work but doesn't flush the writer.

[Close](https://github.com/ipld/go-storethehash/blob/41b16c131842abc8ec6cd4ba236e439d2bf11440/store/freelist/freelist.go#L112) doesn't commit any work, flush it or sync.

My expectation would be that Sync would call Flush which would cause all blocks to be flushed to disk before the sync is performed. This gives the user a way to checkpoint data for integrity. I would normally expect Close to also flush and sync but given the presence of a Sync method then it is perhaps less important.

**Comment by gammazero** [comment]
`freelist.Flush` should definitely flush the writer, and `freelist.Close` should call `freelist.Flush`, as it does for index and primary.

`Sync` is specifically to sync the file to disk, so does not call `Flush`. `Flush` is for writing buffered data to file, not for waiting for it to be committed to a storage device, so does not call `Sync`.  For freelist, index, and primary, `Flush` functions as `bufio.Writer.Flush` and `Sync` as `os.File.Sync`.
