### ISSUE TITLE
Opening a large index takes a long time 

### ISSUE THREAD

**Issue by gammazero** [ipld/go-storethehash#26]
This can take several minutes when the data storage size is a few hundred GB.  The problem is that
[`OpenIndex`](https://github.com/ipld/go-storethehash/blob/abb50f3cc5d01c4d48bfa41de5227157d392311e/store/index/index.go#L92) calls [here](https://github.com/ipld/go-storethehash/blob/abb50f3cc5d01c4d48bfa41de5227157d392311e/store/index/index.go#L129) to `scanIndex` which is defined [here](https://github.com/ipld/go-storethehash/blob/abb50f3cc5d01c4d48bfa41de5227157d392311e/store/index/index.go#L154).  Then `scanIndex` does a sequential scan over the whole index.

**Comment by davidd8** [comment]
Has this been resolved @gammazero? I believe the latest version of STI has fixed the startup times: https://github.com/filecoin-project/storetheindex/tree/v0.4.7

**Comment by willscott** [comment]
yeah, this has been addressed through the multi-file / compaction work.
