### ISSUE TITLE
Runtime GC for primary file

### ISSUE THREAD

**Issue by gammazero** [ipld/go-storethehash#54]
Implement runtime GC for primary file, similar to index GC implementation.

### Split the primary into multiple files.
- Open only the latest primary file for appending.
- Create a new primary and close current when the current primary size becomes >= `maxPrimarySize`.

### Maintain freelist for each primary:
- When freeing a location in a primary the primary file number is known (file number encoded into offset as with index files)
- Update the freelist that corresponds to the primary file with the deleted data.

### Garbage collect stale primaries:
- Periodically scan the freelist of primary(s) not currently open for writing.
- Use the freelist of each primary to determine if all entries in the primary file are no longer used.
- If all entries in primary file are stale, delete primary file and its freelist.

#### Entry counts:
- Maintain an entry count for each primary file (instead of a freelist).
- Increment the entry count when an item is written to the primary, decrement the entry count when an item is deleted from the primary.
- For all but the current primary, remove files that have an entry count of 0.

#### Truncation:
- For each item in the freelist located at the end of the primary file, truncate the primary file by the size indicated by the freelist entry.  This way, primary files that still have current data can be reduced in size.

**Comment by vmx** [comment]
I don't know your workload, but I think this would only work well in a very specific cases. The garbage collection for the indexes uses the fact that it is append-only and that they keys are random and have a normal distribution. Eventual each prefix will be updated (hence have a stale entry). So you only need to have to wait long enough and eventually all entries are stale.

This isn't the case for the primary storage. Some data could just live "forever". The data doesn't get updated, it will only get stale if it is removed. So in worst case one data item in each of the files won't be deleted and you'd end up with no primary file being deleted.

You would need some kind of compaction mechanism when you reach some kind of threshold. Once that threshold is reached, you rewrite the file (a freelist cold be used for that) and update the index.

**Comment by vmx** [comment]
> You would need some kind of compaction mechanism when you reach some kind of threshold. Once that threshold is reached, you rewrite the file (a freelist cold be used for that) and update the index.

One more idea based on this thought. For content addressed data it usually doesn't make sense to update data which has the same key, as the key is the hash of the data. But what if we would allow that. Updating a key-value pair, would just insert it again (perhaps it's already the case, I don't know the current implementation in detail). Then you could just do, what you propose in the original description, but have an additional background process. That process would keep track/scan the primary files to see how much stale data there is. Based on a certain threshold it would start inserting the data again. This way the data would end up in a newer primary file (as we are still append-only). The data would be "deleted" from the old primary files. Eventually the primary file can be deleted.

You could become as smart as you like with the background process. E.g. it could even try to rate limit the re-insertions based on the current insertion rates, or batch things in some way.

**Comment by gammazero** [comment]
Going with the above ideas, and using freelist to efficiently track free primary locations, a background GC cycle could work like this:
- Process freelist and mark primary records as dead(by zeroing the record data). Freelist emptied after this step.
- Scan each primary file, up to but not including current (one being written to), and truncate free records from the end.
  - Opt: Scan starts at the last know in-use location for each file so that entire file is not rescanned each cycle.
- Once file is at low usage threshold (say < 25% of records in use), then rewrite records to store them in latest primary (and update index), and truncate records from file.
  - Opt: Only move the last busy record or two with each GC cycle.
- When the primary file is empty, delete it.

**Comment by vmx** [comment]
> * Scan each primary file, up to but not including current (one being written to), and truncate free records from the end.

What do you mean with "truncate free records"?. Do you mean that it could happen that looking from the end of the file, that there is a continuous section, where all records where deleted, so that you can simply truncate the file?

Is this additional complexity worth it? I guess in your storage pattern it might. But it might make sense to simulate/get some statistics/do early tests before fully implementing it, if it's really worth it. Perhaps the low usage part (which I guess is something that should definitely be implemented) is already good enough.

---

In regards to the freelists. I don't know which data they contain. But if it would be `offset` and `size`, one could determine whether truncation is possible, or the low usage threshold is reached without actually scanning the primary files. You could even "compact" the freelists and make sure that directly adjacent deleted records are combined into a single entry.

Tough I'm not sure if those ideas make things easier or more complex.

**Comment by gammazero** [comment]
@vmx
> Do you mean that it could happen that looking from the end of the file, that there is a continuous section, where all records where deleted, so that you can simply truncate the file?

Yes. I mean delete all contiguous free records from the end of the file by truncating the file.

Truncating the file is efficient and is an effective way of reducing storage, especially as low-usage files are evaporated.  By "evaporated" I mean that each GC cycle moves the last non-free one or two records out of a low-use primary file. Moving these will often allow truncating spans of free records.

I looked at compacting the freelist (merging contiguous free records), and the truncation code actually does the equivalent very efficiently.  It [tracks spans of free records](https://github.com/ipld/go-storethehash/pull/57/files#diff-339abed331540529f949529ffe50e3f6527fd60420a76e6ed75ffce7118ff11fR264-R282) in a primary and [deletes them all](https://github.com/ipld/go-storethehash/pull/57/files#diff-339abed331540529f949529ffe50e3f6527fd60420a76e6ed75ffce7118ff11fR287-R290) if they are at the end of the file.  Creating a merged free record only saves a few reads

**Comment by ribasushi** [comment]
@gammazero @vmx if you haven't already explored it I strongly recommend checking out `fallocate()` in combination with `FALLOC_FL_PUNCH_HOLE` https://man7.org/linux/man-pages/man2/fallocate.2.html

> Within the specified range, partial filesystem blocks are zeroed, and whole filesystem blocks are removed from the file. 
> After a successful call, subsequent reads from this range will return zeros.
> ...
> Not all filesystems support FALLOC_FL_PUNCH_HOLE; if a filesystem doesn't support the operation, an error is returned.
> The operation is supported on at least the following filesystems:
> *  XFS (since Linux 2.6.38)
> *  ext4 (since Linux 3.0)
> *  Btrfs (since Linux 3.7)
> *  [tmpfs(5)](https://man7.org/linux/man-pages/man5/tmpfs.5.html) (since Linux 3.5)
> *  gfs2(5) (since Linux 4.16)

**Comment by gammazero** [comment]
@ribasushi That would allow early recovery of file space on systems where `FALLOC_FL_PUNCH_HOLE` is available.  Same could also be done to index files.
